engines:
  tslint:
    enabled: true
    channel: beta
    config: tslint.json
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - TODO
      - BUG
      - WARNING
      - CAUTION
      - DANGER
      - HACK
  markdownlint:
    enabled: true
ratings:
  paths:
  - "**.ts"
  - "**.md"
exclude_paths:
- node_modules
- "**.d.ts"
