language: node_js
node_js:
   - "0.10"
   - "0.11"
   - "0.12"
   - "iojs"
   - "4"
   - "6"
   - "8"
   - "node"
before_install:
  - "npm install -g typescript"
  - "npm install -g tslint"
  - "npm install -g ts-node"
notifications:
  email:
    recipients:
      - graham@haleyhousellc.com
    on_success: change
    on_failure: always
  slack:
    on_success: change
    on_failure: always